version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"
    ignore:
      # Not currently compatible with ESLint yet
      - dependency-name: typescript
        versions:
          - ">=7, <8"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: node
        versions:
          - ">=25, <26"
          - ">=27, <28"
          - ">=29, <30"
          - ">=31, <32"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"
